### ISSUE TITLE
Error configStore.del is not defined

### ISSUE THREAD

**Issue by lnlwd** [stephenplusplus/gcs-resumable-upload#18]
I got this error while trying to upload a file to GCS

```
/pipeline/source/node_modules/gcs-resumable-upload/index.js:326
  this.configStore.del(this.file)
                   ^

TypeError: this.configStore.del is not a function
    at Upload.deleteConfig (/pipeline/source/node_modules/gcs-resumable-upload/index.js:326:20)
    at Request.<anonymous> (/pipeline/source/node_modules/gcs-resumable-upload/index.js:172:12)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/pipeline/source/node_modules/request/request.js:1171:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/pipeline/source/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by stephenplusplus** [comment]
Thanks for reporting, fixed.
